name: HACLIProxyAPI
version: "1.0.0"
slug: HACLIProxyAPI
description: CLIProxyAPI running in Home Assistant.
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: services
ports:
  8787/tcp: 8787
ports_description:
  8787/tcp: HACLIProxyAPI port
options:
  openai_session_key: ""
  log_level: "info"
schema:
  openai_session_key: str
  log_level: list(debug|info|warning|error)?
