name: HACLIProxyAPI
version: "6.7.21"
slug: hacliproxyapi
description: CLIProxyAPI running in Home Assistant.
url: https://github.com/c128128/HACLIProxyAPI
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: services
hassio_api: true
ports:
  8787/tcp: 8787
ports_description:
  8787/tcp: HACLIProxyAPI port
options:
  session_key: ""
  log_level: "info"
schema:
  session_key: str
  log_level: list(debug|info|warning|error)?
